name: lint-and-test-chart

on:
  pull_request:
    paths:
      - "charts/hajimari/**"
      - ".github/workflows/release-chart.yaml"
      - ".github/workflows/lint-test-chart.yaml"
  push:
    paths:
      - "charts/hajimari/**"
      - ".github/workflows/release-chart.yaml"
      - ".github/workflows/lint-test-chart.yaml"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: default

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint

      - name: Create Kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          wait: 120s
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install
